version: "3.8"
services:
  sesac-user:
    depends_on:
      - rmsoft-mysql
    volumes: 
      - /app/node_modules
      - ./server:/app/
    build: 
      context: ./server
    ports:
      - "8000:8000"
  rmsoft-mysql:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 3331:3306
    environment:
      MYSQL_DATABASE: rmsoft
      MYSQL_ROOT_PASSWORD: rmsoft1!
      MYSQL_USER: hamayj
      MYSQL_PASSWORD: hamayj1!
      TZ: Asia/Seoul
    command:  >
        bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"
